export const MANGA_FIELDS = [
  "title",
  "title_japanese",
  "synopsis",
  "images",
  "chapters",
  "volumes",
  "status",
  "published",
  "score",
  "background",
  "authors",
  "serializations",
  "genres",
  "themes",
  "demographics",
  "relations",
];

export const ANIME_FIELDS = [
  "title",
  "title_japanese",
  "synopsis",
  "images",
  //   "trailer",
  "episodes",
  "status",
  "airing",
  "aired",
  "duration",
  "rating",
  "score",
  "background",
  "season",
  "year",
  //   "broadcast",
  //   "producers",
  //   "licensors",
  //   "studios",
  "genres",
  "themes",
  "demographics",
  "relations",
  //   "theme",
  //   "streaming",
];

export const CHARACTER_FIELDS = [
  "name",
  "name_kanji",
  "nicknames",
  "about",
  //   "anime",
  //   "manga",
  //   "voices",
];
